---
sudo: true

language: java

jdk: openjdk8

env:
  - OPENCAST_BRANCH=develop OPENCAST_MVN_VERSION=10-SNAPSHOT
  - OPENCAST_BRANCH=r/9.x OPENCAST_MVN_VERSION=9-SNAPSHOT
  - OPENCAST_BRANCH=8.10 OPENCAST_MVN_VERSION=8.10
  - OPENCAST_BRANCH=9.2 OPENCAST_MVN_VERSION=9.2

#install:
#  - git clone https://github.com/opencast/opencast.git --branch $OPENCAST_BRANCH ../opencast
#  - ( cd ../opencast && mvn --quiet --batch-mode install -DskipTests=true -Dcheckstyle.skip=true -DskipJasmineTests=true -Pnone )

before_script:
  - sed -i "s|<version>.*-SNAPSHOT</version>|<version>$OPENCAST_MVN_VERSION</version>|" pom.xml

script:
  - mvn -B clean install


deploy:
  - provider: releases
    api_key:
      secure: nmjIncsp2ZuZHLj9O16YCJdms0seB0UC5XyeSznhdtRi5RQcNALveRPtk9dLYb8GAI66A+b0Uqw43gVuj6A8ejTJgDdXlSHJtSHbsZDZJaIOP3JQnz9kSJg13l5sOGOE00ALPuJe+zpErACVLYnrw3x7TIoMZM5jGjobyX6vkfg=
    skip_cleanup: true
    file:
      - /home/travis/.m2/repository/org/opencastproject/opencast-engage-paella-player/${OPENCAST_MVN_VERSION}/opencast-engage-paella-player-${OPENCAST_MVN_VERSION}.jar
    on:
      repo: polimediaupv/paella-opencast
      tags: true
      
