name: Test Paella 7

on:
  push:
    paths:
      - 'opencast/docs/checkstyle/**'
      - 'opencast/modules/engage-paella-player-7/**'
  pull_request:
    paths:
      - 'opencast/docs/checkstyle/**'
      - 'opencast/modules/engage-paella-player-7/**'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        cd opencast/modules/engage-paella-player-7
        npm ci

    - name: Install Playwright Browsers
      run: |
        cd opencast/modules/engage-paella-player-7
        npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        cd opencast/modules/engage-paella-player-7
        npm run test -- --project='firefox' --project='Google Chrome'

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: opencast/modules/engage-paella-player-7/playwright-report/
        retention-days: 30
